export const appointments = [
  {
    id: 'VX-2026-0915-0830',
    status: 'upcoming',
    day: '15',
    month: 'Th9',
    title: 'HPV – Mũi 2',
    line1: 'VaxCare Trung Mỹ Tây · 08:30–09:00',
    line2: 'Số 8 Nguyễn Thị Trên, P. Trung Mỹ Tây, TP.HCM',
    statusLabel: 'Sắp tới',
  },
  {
    id: null,
    status: 'completed',
    day: '12',
    month: 'Th3',
    dateStyle: { background: 'var(--mint-100)' },
    dayStyle: { color: 'var(--teal-700)' },
    monthStyle: { color: 'var(--teal-600)' },
    title: 'HPV – Mũi 1',
    line1: 'VaxCare Quận 1 · 09:00–09:30',
    line2: 'Đã tiêm · Lô A12345',
    statusLabel: 'Đã tiêm',
  },
  {
    id: null,
    status: 'completed',
    day: '05',
    month: 'Th11',
    dateStyle: { background: 'var(--mint-100)' },
    dayStyle: { color: 'var(--teal-700)' },
    monthStyle: { color: 'var(--teal-600)' },
    title: 'Cúm mùa 2025',
    line1: 'VaxCare Bình Thạnh · 14:00–14:30',
    line2: 'Đã tiêm · Lô B7788',
    statusLabel: 'Đã tiêm',
  },
  {
    id: null,
    status: 'cancelled',
    day: '20',
    month: 'Th2',
    dateStyle: { background: '#fef2f2' },
    dayStyle: { color: '#c0392b' },
    monthStyle: { color: '#c0392b' },
    title: 'Viêm gan A',
    line1: 'VaxCare Gò Vấp · 10:00–10:30',
    line2: null,
    statusLabel: 'Đã hủy',
    cancelledNote: 'Hủy ngày 18/02/2026',
  },
];

export const appointmentFilters = [
  { key: 'all', label: 'Tất cả' },
  { key: 'upcoming', label: 'Sắp tới' },
  { key: 'completed', label: 'Đã tiêm' },
  { key: 'cancelled', label: 'Đã hủy' },
];
